# Generated by Django 5.1.3 on 2024-12-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_category_slug_product_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=' ', upload_to='category-img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(default=' ', upload_to='subcategory-img'),
            preserve_default=False,
        ),
    ]
