# Generated by Django 5.1.3 on 2024-12-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_category_img_subcategory_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
    ]
